export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Jobs } from "./Jobs";
export { default as Layout } from "./Layout/Layout";
// export { default as Meta } from "./Meta";
export { default as Navbar } from "./Navbar";
export { default as Services } from "./Services";
export { default as Seo } from "./SEO";
export { default as Title } from "./Title";
// export { default as ContextWrapper } from "./constants/ContextWrapper";
// export { default as Links } from "./constants/links";
